WORK_OUT_TYPES_BY_DICT = {
    'HIIT-7/4': {
        'SINGLE_WORKOUT_TIME_IN_SECONDS': 40,
        'BREAK_TIME_BETWEEN_WORKOUTS_IN_SECONDS': 15,
        'BREAK_TIME_BETWEEN_ROUNDS_IN_SECONDS': 60,
        'WORK_OUT_NUMBER_PER_SESSION': 7,
        'TOTAL_NUMBER_OF_ROUNDS': 4,
    },
    'SC-23': {
        'SINGLE_WORKOUT_TIME_IN_SECONDS': 23,
        'BREAK_TIME_BETWEEN_WORKOUTS_IN_SECONDS': 5,
        'BREAK_TIME_BETWEEN_ROUNDS_IN_SECONDS': 60,
        'WORK_OUT_NUMBER_PER_SESSION': 8,
        'TOTAL_NUMBER_OF_ROUNDS': 3,
    },
}
